### ISSUE TITLE
Use projects stylelint if it exists

### ISSUE THREAD

**Issue by chrishoage** [olegskl/gulp-stylelint#35] opened 2016-08-04 20:59 UTC
We have `stylelint` in our project that is required as a peer dependency for some other tools. It would be nice to be able to use that version of `stylelint` instead of forcing the version that ships with `gulp-stylelint`

**Comment by olegskl** [comment] 2016-08-05 10:31
I'm not really in favor of peer dependencies. Sure they are useful to some people, but they create a whole lot of trouble for the majority of users.

**Comment by chrishoage** [comment] 2016-08-05 16:52
Yes sorry I didn't mean to suggest to use peer dependencies, what I am suggesting is to attempt to resolve the `stylelint` package from the projects `node_modules` before loading `gulp-stylelints` own `stylelint` dependency. That way _if_ a project wanted to manage the `stylelint` version they could do so. 

I was thinking something similar to how `eslint_d` handles it: https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js

**Comment by woble** [comment] 2016-08-12 05:52
@olegskl 
How do you suggest going about updating `stylelint` without reinstalling `gulp-stylelint` every time `stylelint` releases a minor version?

**Comment by olegskl** [comment] 2016-08-12 08:36
@woble You don't need to reinstall gulp-stylelint every time stylelint releases a minor version.

**Comment by olegskl** [comment] 2016-08-12 08:50
@chrishoage Sorry for late response. I just... really, really don't want to add complexity to the library that uses the latest versions of its dependencies. People will install an unsupported version of stylelint and start asking questions "why isn't gulp-stylelint working?".

If you want to use a certain version of stylelint, you can:
 1. Use it directly in gulp without gulp-stylelint (you will lose some nice functionality though).
 2. Install a previous version of gulp-stylelint (I recall that 1.1.0 and 2.0.2 did work well with previous versions of stylelint).
 3. Fork?

Or maybe you can persuade the guys working on "some other tools" you mentioned, to actually support the latest version of stylelint.

**Comment by woble** [comment] 2016-08-12 09:48
@olegskl 
Unless I am doing something wrong or I am not aware of something, `npm up` does not update gulp-stylelint (because still v3.0.0) with the latest version of stylelint. Doing `npm up stylelint` is not desired as it could install unsupported version of stylelint and break gulp-stylelint, you say that yourself.

We don't use stylelint for anything else other than gulp-stylelint, but as new versions of stylelint roll in, updating has to be forced through `npm up stylelint` on each dev machine. Having it as peer dependency will eliminate that problem and a simple `npm up` will update all packages as needed.

[gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint) uses tslint as peer dependency and it works just fine as they keep track of supported tslint versions.

**Comment by olegskl** [comment] 2016-08-12 10:09
@woble I don't understand the issue.

Suppose you have gulp-stylelint v3.0.0 and stylelint v7.0.0. If stylelint releases a new minor version (for example, v7.0.1 or v7.1.0 or v7.6.8) and you do an `npm update`, then what happens is that a new version of stylelint will be installed, but gulp-stylelint will stay at v3.0.0 because it's supposed to work with all minor releases of stylelint up to v7.9999.9999999-whatever.

If, however, stylelint goes to v8.x.x (a major release), then I will need to update gulp-stylelint to v.4.0.0 and when you do `npm update` both stylelint and gulp-stylelint will be reinstalled.

**Comment by woble** [comment] 2016-08-12 10:35
`npm update` only updates packages listed in package.json, not dependencies of those packages, thus stylelint will only update if gulp-stylelint updates.

**Comment by olegskl** [comment] 2016-08-12 11:37
Okay, I was ill-informed. I could automatically release a new version of gulp-stylelint when its dependencies change. What do you think?

**Comment by jeddy3** [comment] 2016-08-12 13:33
Wouldn't `npm update --depth 1` work?

**Comment by olegskl** [comment] 2016-08-12 13:46
@jeddy3 Do you requiring stylelint as a peer dependency is better than the current approach?

**Comment by jeddy3** [comment] 2016-08-12 14:08
I dunno I'm afraid. I'm not very familiar with authoring gulp plugins. It looks like `gulp-eslint` (it's well used with 400k monthly downloads) uses the same approach you're currently using i.e. has `eslint` as a caret dependency. There appears to be a discussion for it here: https://github.com/adametry/gulp-eslint/issues/68.

**Comment by thomas-darling** [comment] 2016-08-12 14:41
Well, then `gulp-eslint` is doing it wrong too :-)

This is exactly what peer-dependencies are for, and it works perfectly for e.g. `gulp-tslint`, which also has a massive number of users. I really don't see what the problem is - having it as a peer dependency allows us to update `stylelint` independent of `gulp-stylelint`, and if an incompatible version is installed, we get a warning. Perfect.

For reference:

https://nodejs.org/en/blog/npm/peer-dependencies

http://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins/34645112#34645112

Also note:

> As of npm@2.6.1, the npm update will only inspect top-level packages. Prior versions of npm would also recursively inspect all dependencies. To get the old behavior, use npm --depth Infinity update, but be warned that simultaneous asynchronous update of all packages, including npm itself and packages that npm depends on, often causes problems up to and including the uninstallation of npm itself.
https://docs.npmjs.com/cli/update

**Comment by woble** [comment] 2017-09-26 07:01
https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#peer-dependencies

**Comment by olegskl** [comment] 2017-11-03 10:19
Commit a26f7be4ca167ab204e0e5a041275dc07981572f will require stylelint as a peer dependency. Will be released in 6.0.0.

**Comment by olegskl** [comment] 2018-01-02 13:58
Done in 36c16eef26ee8065b64014dda4414cdb449f5ec2 and published in [6.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/6.0.0).

**Closed by olegskl** 2018-01-02 13:58 UTC
