### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by thasmo** [olegskl/gulp-stylelint#39] opened 2016-08-17 22:22 UTC
When running `gulp-stylelint` there's an error `Cannot read property '0' of undefined` and files don't get linted. Running the `stylelint` CLI directly on the files works.

The console log:
```
[00:18:42] TypeError in plugin 'gulp-stylelint'
Message:
    Cannot read property '0' of undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

My gulp task looks like this:
```js
return gulp.src('path/**/*.scss').pipe(stylelint({
	reporters: [
		{
			formatter: 'verbose',
			console: true
		}
	]
}));
```

`gulp --version`:
```
CLI version 1.2.2
Local version 4.0.0-alpha.2
```

I'm using `gulp-stylelint` on version 3.1.

**Comment by olegskl** [comment] 2016-08-18 00:06
I didn't actually expect it to work with gulp 4 at all. However it *seems* to work fine. I've created a test repository here: [gulp-stylelint-test](https://github.com/olegskl/gulp-stylelint-test). Can you try to clone, `npm install`, `npm run lint` it?

**Comment by thasmo** [comment] 2016-08-20 13:03
Thanks for providing the test-case! I tried it and ir works. Unfortunately in my case it doesn't and I'm still wondering why. I will investigate further occasionally, but feel free to close this issue.

**Comment by olegskl** [comment] 2016-08-20 13:14
Let's keep it open for the time being, I'll do some investigation on my side as well.

**Comment by NejcZdovc** [comment] 2016-08-23 11:10
Hi. I am having the same problem. Problem occured when I updated from version 2.0.2 to 3.1.0.

This is my error:
```Message:
Cannot read property '0' of undefined
Stack:
TypeError: Cannot read property '0' of undefined
    at node_modules/stylelint/dist/formatters/jsonFormatter.js:10:17
    at node_modules/lodash/lodash.js:11233:17
    at node_modules/lodash/lodash.js:3085:13
    at node_modules/lodash/lodash.js:3925:15
    at baseForIn (node_modules/lodash/lodash.js:2509:40)
    at basePickBy (node_modules/lodash/lodash.js:3084:7)
    at Function.omitBy (node_modules/lodash/lodash.js:11232:14)
    at node_modules/stylelint/dist/formatters/jsonFormatter.js:9:29
    at Array.map (native)
    at exports.default (node_modules/stylelint/dist/formatters/jsonFormatter.js:8:32)
```

Hope this helps in anyway finding the bug.

**Comment by olegskl** [comment] 2016-08-23 13:57
Isn't it weird that the error gets thrown from `jsonFormatter` when you're using `verboseFormatter`? Also, what is `stylelint` in your code: [`stylelint`](https://github.com/stylelint/stylelint) or [`gulp-stylelint`](https://github.com/olegskl/gulp-stylelint)?

**Comment by NejcZdovc** [comment] 2016-08-23 16:07
I tried switching to string, but I got the same error. I tried also something like this, but again same error.

``

**Comment by olegskl** [comment] 2016-08-23 16:43
I'm under the impression that this is not the code that generates the error. That would explain the reason the error is thrown from `jsonFormatter` which is not mentioned in your code. Sorry for being naive, but if you comment out the code you provided, does the error go away?

If you can create a small reproducible test case (you can make a pull request to [gulp-stylelint-test](https://github.com/olegskl/gulp-stylelint-test) if you wish) that would help a lot.

**Comment by NejcZdovc** [comment] 2016-08-23 19:10
Ok, will try to prepare it tomorrow.

**Comment by sbaechler** [comment] 2016-09-20 12:55
This looks like a bug in stylelint 7.3.0. It will be fixed in 7.3.1.
https://github.com/stylelint/stylelint/issues/1914

I would suggest to fix the stylelint dependency to ~7.2.0 until 7.3.1 is released.

**Comment by olegskl** [comment] 2016-09-20 22:55
I'll up to 7.3.1 first thing tomorrow morning. Too much beer today... sorry for delays...

**Comment by olegskl** [comment] 2016-09-21 08:30
Version 3.3.0 pointing to [stylelint 7.3.1](https://github.com/stylelint/stylelint/releases/tag/7.3.1) has been [released](https://github.com/olegskl/gulp-stylelint/releases/tag/3.3.0) and published to npm.

**Comment by olegskl** [comment] 2016-10-05 08:26
I'm assuming this has been resolved by the latest release.

**Closed by olegskl** 2016-10-05 08:26 UTC
